substitutions:
  ext_comp_repo_ref: copilot/reapply-changes-from-feat-mww-audio-trigger

external_components:
  - source:
      type: git
      url: https://github.com/constructorfleet/satellite1-esphome
      ref: ${ext_comp_repo_ref}
    components:
      - audio
      - micro_wake_word
      - mixer
      - resampler
      - snapcast
      - speaker
      - version

  - source:
      # https://github.com/esphome/esphome/pull/12429
      type: git
      url: https://github.com/esphome/esphome
      ref: ff8ce89556748509d7ee8724e12d9d43d3c8c1e8
    refresh: 300s
    components: [http_request]
